package co.edu.udea.compumovil.gr04_20262.lab1.ui.theme

import androidx.compose.ui.graphics.Color

// Paleta Material 3 - verde azulado (teal)

// Light
val md_primary = Color(0xFF006A6A)
val md_onPrimary = Color(0xFFFFFFFF)
val md_primaryContainer = Color(0xFF6FF7F6)
val md_onPrimaryContainer = Color(0xFF002020)
val md_secondary = Color(0xFF4A6363)
val md_onSecondary = Color(0xFFFFFFFF)
val md_secondaryContainer = Color(0xFFCCE8E7)
val md_onSecondaryContainer = Color(0xFF051F1F)
val md_tertiary = Color(0xFF4B607C)
val md_onTertiary = Color(0xFFFFFFFF)
val md_tertiaryContainer = Color(0xFFD3E4FF)
val md_onTertiaryContainer = Color(0xFF041C35)
val md_error = Color(0xFFBA1A1A)
val md_onError = Color(0xFFFFFFFF)
val md_errorContainer = Color(0xFFFFDAD6)
val md_onErrorContainer = Color(0xFF410002)
val md_background = Color(0xFFF4FBFA)
val md_onBackground = Color(0xFF161D1D)
val md_surface = Color(0xFFF4FBFA)
val md_onSurface = Color(0xFF161D1D)
val md_surfaceVariant = Color(0xFFDAE5E3)
val md_onSurfaceVariant = Color(0xFF3F4948)
val md_outline = Color(0xFF6F7979)
val md_surfaceContainer = Color(0xFFE8EFEE)

// Dark
val md_primary_d = Color(0xFF4CDADA)
val md_onPrimary_d = Color(0xFF003737)
val md_primaryContainer_d = Color(0xFF004F4F)
val md_onPrimaryContainer_d = Color(0xFF6FF7F6)
val md_secondary_d = Color(0xFFB0CCCB)
val md_onSecondary_d = Color(0xFF1B3534)
val md_secondaryContainer_d = Color(0xFF324B4B)
val md_onSecondaryContainer_d = Color(0xFFCCE8E7)
val md_tertiary_d = Color(0xFFB3C8E8)
val md_onTertiary_d = Color(0xFF1C314B)
val md_tertiaryContainer_d = Color(0xFF334863)
val md_onTertiaryContainer_d = Color(0xFFD3E4FF)
val md_error_d = Color(0xFFFFB4AB)
val md_onError_d = Color(0xFF690005)
val md_errorContainer_d = Color(0xFF93000A)
val md_onErrorContainer_d = Color(0xFFFFDAD6)
val md_background_d = Color(0xFF0E1414)
val md_onBackground_d = Color(0xFFDDE4E3)
val md_surface_d = Color(0xFF0E1414)
val md_onSurface_d = Color(0xFFDDE4E3)
val md_surfaceVariant_d = Color(0xFF3F4948)
val md_onSurfaceVariant_d = Color(0xFFBEC9C8)
val md_outline_d = Color(0xFF889392)
val md_surfaceContainer_d = Color(0xFF1B2120)
